<?php
$pageTitle = "Reports";
include_once '../includes/header.php';
include_once '../includes/db_connection.php';
?>

<div class="d-flex justify-content-between align-items-center mb-4">
    <h2>Monthly Reports</h2>
</div>

<div class="form-container mb-4">
    <form action="generate_report.php" method="get">
        <div class="row align-items-end">
            <div class="col-md-4">
                <label for="report_month" class="form-label">Month</label>
                <input type="month" class="form-control" id="report_month" name="report_month" value="<?php echo date('Y-m'); ?>" required>
            </div>
            <div class="col-md-6">
                <label for="report_type" class="form-label">Report Type</label>
                <select class="form-select" id="report_type" name="report_type" required>
                    <option value="">Select Report Type</option>
                    <option value="mileage_by_vehicle">Mileage Driven by Vehicle</option>
                    <option value="mileage_by_department">Mileage Driven by Department</option>
                    <option value="mileage_by_faculty">Mileage Driven by Faculty</option>
                    <option value="revenue_by_vehicle">Fee Revenue by Vehicle</option>
                    <option value="revenue_by_department">Fee Revenue by Department</option>
                    <option value="parts_usage">Parts Usage Report</option>
                    <option value="maintenance_summary">Vehicle Maintenance Summary</option>
                </select>
            </div>
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary w-100">Generate Report</button>
            </div>
        </div>
    </form>
</div>

<div class="card">
    <div class="card-header">
        Available Reports
    </div>
    <div class="card-body">
        <div class="list-group">
            <a href="generate_report.php?report_type=mileage_by_vehicle&report_month=<?php echo date('Y-m'); ?>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Mileage Driven by Vehicle</h5>
                </div>
                <p class="mb-1">Shows total miles driven by each vehicle in the selected month.</p>
            </a>
            <a href="generate_report.php?report_type=mileage_by_department&report_month=<?php echo date('Y-m'); ?>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Mileage Driven by Department</h5>
                </div>
                <p class="mb-1">Shows total miles driven by each department in the selected month.</p>
            </a>
            <a href="generate_report.php?report_type=mileage_by_faculty&report_month=<?php echo date('Y-m'); ?>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Mileage Driven by Faculty</h5>
                </div>
                <p class="mb-1">Shows total miles driven by each faculty member in the selected month.</p>
            </a>
            <a href="generate_report.php?report_type=revenue_by_vehicle&report_month=<?php echo date('Y-m'); ?>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Fee Revenue by Vehicle</h5>
                </div>
                <p class="mb-1">Shows total fee revenue generated by each vehicle in the selected month.</p>
            </a>
            <a href="generate_report.php?report_type=revenue_by_department&report_month=<?php echo date('Y-m'); ?>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Fee Revenue by Department</h5>
                </div>
                <p class="mb-1">Shows total fee revenue charged to each department in the selected month.</p>
            </a>
            <a href="generate_report.php?report_type=parts_usage&report_month=<?php echo date('Y-m'); ?>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Parts Usage Report</h5>
                </div>
                <p class="mb-1">Shows detailed parts usage information for the selected month.</p>
            </a>
            <a href="generate_report.php?report_type=maintenance_summary&report_month=<?php echo date('Y-m'); ?>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Vehicle Maintenance Summary</h5>
                </div>
                <p class="mb-1">Shows summary of maintenance activities for each vehicle in the selected month.</p>
            </a>
        </div>
    </div>
</div>

<?php include_once '../includes/footer.php'; ?>