CREATE DATABASE IF NOT EXISTS tiny_college_vmdb;
USE tiny_college_vmdb;

CREATE TABLE DEPARTMENT (
	DEPARTMENT_CODE VARCHAR(20)  NOT NULL,
	DEPARTMENT_NAME VARCHAR(99)  NOT NULL,
	PRIMARY KEY (DEPARTMENT_CODE),
	CONSTRAINT UQ_DEPARTMENT_NAME UNIQUE (DEPARTMENT_NAME)
);

CREATE TABLE FACULTY (
	FACULTY_ID      INT          NOT NULL,
	DEPARTMENT_CODE VARCHAR(20)  NOT NULL,
	FACULTY_LNAME   VARCHAR(99)  NOT NULL,
	FACULTY_FNAME   VARCHAR(99)  NOT NULL,
	FACULTY_EMAIL   VARCHAR(99)  NOT NULL,
	PRIMARY KEY (FACULTY_ID),
	CONSTRAINT UQ_FACULTY_EMAIL UNIQUE (FACULTY_EMAIL),
	CONSTRAINT FK_FACULTY_DEPARTMENT
		FOREIGN KEY (DEPARTMENT_CODE)
		REFERENCES DEPARTMENT (DEPARTMENT_CODE)
		ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE VEHICLE_TYPE (
	VEHICLE_TYPE VARCHAR(20)  NOT NULL,
	MILEAGE_RATE DECIMAL(5,2) NOT NULL CHECK (MILEAGE_RATE >= 0 AND MILEAGE_RATE <= 999.99),
	PRIMARY KEY (VEHICLE_TYPE)
);

CREATE TABLE VEHICLE (
	VEHICLE_ID        INT          NOT NULL,
	VEHICLE_TYPE      VARCHAR(20)  NOT NULL,
	VEHICLE_MAKEMODEL VARCHAR(99)  NOT NULL,
	VEHICLE_YEAR      INT          NOT NULL CHECK (VEHICLE_YEAR BETWEEN 1900 AND 2100),
	VEHICLE_PLATE     VARCHAR(20)  NOT NULL,
	VEHICLE_VIN       VARCHAR(20)  NOT NULL,
	VEHICLE_ODOMETER  INT          NOT NULL CHECK (VEHICLE_ODOMETER >= 0 AND VEHICLE_ODOMETER <= 9999999),
	VEHICLE_STATUS    VARCHAR(20)  NOT NULL,
	PRIMARY KEY (VEHICLE_ID),
	CONSTRAINT UQ_VEHICLE_PLATE UNIQUE (VEHICLE_PLATE),
	CONSTRAINT UQ_VEHICLE_VIN   UNIQUE (VEHICLE_VIN),
	CONSTRAINT FK_VEHICLE_VEHICLE_TYPE
		FOREIGN KEY (VEHICLE_TYPE)
		REFERENCES VEHICLE_TYPE (VEHICLE_TYPE)
		ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE RESERVATION (
	RESERVATION_ID     INT          NOT NULL,
	DEPARTMENT_CODE    VARCHAR(20)  NOT NULL,
	FACULTY_ID         INT          NOT NULL,
	VEHICLE_TYPE       VARCHAR(20)  NOT NULL,
	EXPECTED_DEPARTURE DATE         NOT NULL,
	EXPECTED_RETURN    DATE         NOT NULL CHECK (EXPECTED_RETURN >= EXPECTED_DEPARTURE),
	DESTINATION        VARCHAR(99)  NOT NULL,
	PRIMARY KEY (RESERVATION_ID),
	CONSTRAINT FK_RESERVATION_DEPARTMENT
		FOREIGN KEY (DEPARTMENT_CODE)
		REFERENCES DEPARTMENT (DEPARTMENT_CODE)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_RESERVATION_FACULTY
		FOREIGN KEY (FACULTY_ID)
		REFERENCES FACULTY (FACULTY_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_RESERVATION_VEHICLE_TYPE
		FOREIGN KEY (VEHICLE_TYPE)
		REFERENCES VEHICLE_TYPE (VEHICLE_TYPE)
		ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE CHECKOUT (
	CHECKOUT_ID    INT  NOT NULL,
	RESERVATION_ID INT  NOT NULL,
	VEHICLE_ID     INT  NOT NULL,
	FACULTY_ID     INT  NOT NULL,
	CHECKOUT_DATE  DATE NOT NULL,
	PRIMARY KEY (CHECKOUT_ID),
	CONSTRAINT UQ_CHECKOUT_RESERVATION UNIQUE (RESERVATION_ID),
	CONSTRAINT FK_CHECKOUT_RESERVATION
		FOREIGN KEY (RESERVATION_ID)
		REFERENCES RESERVATION (RESERVATION_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_CHECKOUT_VEHICLE
		FOREIGN KEY (VEHICLE_ID)
		REFERENCES VEHICLE (VEHICLE_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_CHECKOUT_FACULTY
		FOREIGN KEY (FACULTY_ID)
		REFERENCES FACULTY (FACULTY_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE TRIP_COMPLETION (
	TRIP_ID                INT           NOT NULL,
	CHECKOUT_ID            INT           NOT NULL,
	FACULTY_ID             INT           NOT NULL,
	ODOMETER_START         INT           NOT NULL CHECK (ODOMETER_START >= 0 AND ODOMETER_START <= 9999999),
	ODOMETER_END           INT           NOT NULL CHECK (ODOMETER_END >= 0 AND ODOMETER_END <= 9999999 AND ODOMETER_END >= ODOMETER_START),
	MAINTENANCE_COMPLAINTS VARCHAR(300),
	FUEL_PURCHASED_GALLONS DECIMAL(5,2)  CHECK (FUEL_PURCHASED_GALLONS >= 0 AND FUEL_PURCHASED_GALLONS <= 999.99),
	FUEL_COST              DECIMAL(7,2)  CHECK (FUEL_COST >= 0 AND FUEL_COST <= 99999.99),
	CREDIT_CARD_NUM        VARCHAR(99),
	RETURN_DATE            DATE          NOT NULL,
	MILEAGE_BILL           DECIMAL(7,2)  NOT NULL CHECK (MILEAGE_BILL >= 0 AND MILEAGE_BILL <= 99999.99),
	PRIMARY KEY (TRIP_ID),
	CONSTRAINT UQ_TRIP_COMPLETION_CHECKOUT UNIQUE (CHECKOUT_ID),
	CONSTRAINT FK_TC_CHECKOUT
		FOREIGN KEY (CHECKOUT_ID)
		REFERENCES CHECKOUT (CHECKOUT_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_TC_FACULTY
		FOREIGN KEY (FACULTY_ID)
		REFERENCES FACULTY (FACULTY_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE MECHANIC (
	MECHANIC_ID    INT         NOT NULL,
	MECHANIC_LNAME VARCHAR(99) NOT NULL,
	MECHANIC_FNAME VARCHAR(99) NOT NULL,
	IS_AUTHORIZED  BOOLEAN     NOT NULL CHECK (IS_AUTHORIZED >= 0 AND IS_AUTHORIZED <= 1),
	PRIMARY KEY (MECHANIC_ID)
);

CREATE TABLE MAINTENANCE_LOG (
	LOG_ID                      INT          NOT NULL,
	VEHICLE_ID                  INT          NOT NULL,
	DESCRIPTION                 VARCHAR(300) NOT NULL,
	LOG_START_DATE              DATE         NOT NULL,
	MAINTENANCE_COMPLETION_DATE DATE,
	RELEASE_MECHANIC_ID         INT,
	PRIMARY KEY (LOG_ID),
	CONSTRAINT FK_ML_VEHICLE
		FOREIGN KEY (VEHICLE_ID)
		REFERENCES VEHICLE (VEHICLE_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_ML_RELEASE_MECHANIC
		FOREIGN KEY (RELEASE_MECHANIC_ID)
		REFERENCES MECHANIC (MECHANIC_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE PART_TYPE (
	PART_ID          INT         NOT NULL,
	PART_NAME        VARCHAR(99) NOT NULL,
	QUANTITY_ON_HAND INT         NOT NULL CHECK (QUANTITY_ON_HAND >= 0 AND QUANTITY_ON_HAND <= 999),
	MINIMUM_QUANTITY INT         NOT NULL CHECK (MINIMUM_QUANTITY >= 0 AND MINIMUM_QUANTITY <= 999),
	PRIMARY KEY (PART_ID),
	CONSTRAINT UQ_PART_NAME UNIQUE (PART_NAME)
);

CREATE TABLE MAINTENANCE_ITEM (
	LOG_ID           INT         NOT NULL,
	LINE_NUMBER      INT         NOT NULL CHECK (LINE_NUMBER >= 0 AND LINE_NUMBER <= 99),
	ITEM_DESCRIPTION VARCHAR(99) NOT NULL,
	PART_ID          INT         NOT NULL,
	MECHANIC_ID      INT         NOT NULL,
	PRIMARY KEY (LOG_ID, LINE_NUMBER),
	CONSTRAINT FK_MI_LOG
		FOREIGN KEY (LOG_ID)
		REFERENCES MAINTENANCE_LOG (LOG_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_MI_PART
		FOREIGN KEY (PART_ID)
		REFERENCES PART_TYPE (PART_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT FK_MI_MECHANIC
		FOREIGN KEY (MECHANIC_ID)
		REFERENCES MECHANIC (MECHANIC_ID)
		ON UPDATE RESTRICT ON DELETE RESTRICT
);










INSERT INTO DEPARTMENT (DEPARTMENT_CODE, DEPARTMENT_NAME) VALUES
('CS', 'Computer Science'),
('ENG', 'Engineering'),
('MATH', 'Mathematics'),
('BIO', 'Biology'),
('BUS', 'Business'),
('ART', 'Art');

INSERT INTO FACULTY (FACULTY_ID, DEPARTMENT_CODE, FACULTY_LNAME, FACULTY_FNAME, FACULTY_EMAIL) VALUES
(1, 'CS', 'Smith', 'John', 'jsmith@tinycollege.edu'),
(2, 'ENG', 'Johnson', 'Emily', 'ejohnson@tinycollege.edu'),
(3, 'MATH', 'Brown', 'Michael', 'mbrown@tinycollege.edu'),
(4, 'BIO', 'Davis', 'Sarah', 'sdavis@tinycollege.edu'),
(5, 'BUS', 'Miller', 'David', 'dmiller@tinycollege.edu'),
(6, 'ART', 'Wilson', 'Laura', 'lwilson@tinycollege.edu');

INSERT INTO VEHICLE_TYPE (VEHICLE_TYPE, MILEAGE_RATE) VALUES
('Sedan', 0.45),
('SUV', 0.55),
('Van', 0.60),
('Truck', 0.65),
('Hybrid', 0.40),
('Electric', 0.35);

INSERT INTO VEHICLE (VEHICLE_ID, VEHICLE_TYPE, VEHICLE_MAKEMODEL, VEHICLE_YEAR, VEHICLE_PLATE, VEHICLE_VIN, VEHICLE_ODOMETER, VEHICLE_STATUS) VALUES
(1, 'Sedan', 'Toyota Camry', 2020, 'ABC123', 'VIN00001', 25000, 'Available'),
(2, 'SUV', 'Honda CR-V', 2019, 'XYZ789', 'VIN00002', 40000, 'Available'),
(3, 'Van', 'Ford Transit', 2021, 'VAN456', 'VIN00003', 15000, 'Available'),
(4, 'Truck', 'Chevy Silverado', 2018, 'TRK111', 'VIN00004', 50000, 'Maintenance'),
(5, 'Hybrid', 'Toyota Prius', 2022, 'HYB222', 'VIN00005', 8000, 'Available'),
(6, 'Electric', 'Tesla Model 3', 2023, 'ELE333', 'VIN00006', 5000, 'Available');

INSERT INTO RESERVATION (RESERVATION_ID, DEPARTMENT_CODE, FACULTY_ID, VEHICLE_TYPE, EXPECTED_DEPARTURE, EXPECTED_RETURN, DESTINATION) VALUES
(1, 'CS', 1, 'Sedan', '2025-09-01', '2025-09-05', 'Conference Center'),
(2, 'ENG', 2, 'SUV', '2025-09-02', '2025-09-04', 'Research Facility'),
(3, 'MATH', 3, 'Van', '2025-09-03', '2025-09-06', 'Math Symposium'),
(4, 'BIO', 4, 'Truck', '2025-09-05', '2025-09-07', 'Field Station'),
(5, 'BUS', 5, 'Hybrid', '2025-09-08', '2025-09-10', 'Business Expo'),
(6, 'ART', 6, 'Electric', '2025-09-09', '2025-09-11', 'Art Fair');

INSERT INTO CHECKOUT (CHECKOUT_ID, RESERVATION_ID, VEHICLE_ID, FACULTY_ID, CHECKOUT_DATE) VALUES
(1, 1, 1, 1, '2025-09-01'),
(2, 2, 2, 2, '2025-09-02'),
(3, 3, 3, 3, '2025-09-03'),
(4, 4, 4, 4, '2025-09-05'),
(5, 5, 5, 5, '2025-09-08'),
(6, 6, 6, 6, '2025-09-09');

INSERT INTO TRIP_COMPLETION (TRIP_ID, CHECKOUT_ID, FACULTY_ID, ODOMETER_START, ODOMETER_END, MAINTENANCE_COMPLAINTS, FUEL_PURCHASED_GALLONS, FUEL_COST, CREDIT_CARD_NUM, RETURN_DATE, MILEAGE_BILL) VALUES
(1, 1, 1, 25000, 25300, NULL, 10.5, 35.00, '1234567890123456', '2025-09-05', 135.00),
(2, 2, 2, 40000, 40350, 'Engine noise', 12.0, 42.00, '2345678901234567', '2025-09-04', 192.50),
(3, 3, 3, 15000, 15200, NULL, 8.0, 28.00, '3456789012345678', '2025-09-06', 120.00),
(4, 4, 4, 50000, 50250, 'Tire wear', 15.0, 55.00, '4567890123456789', '2025-09-07', 162.50),
(5, 5, 5, 8000, 8200, NULL, 7.5, 27.50, '5678901234567890', '2025-09-10', 80.00),
(6, 6, 6, 5000, 5150, 'Charging cable issue', NULL, NULL, NULL, '2025-09-11', 52.50);

INSERT INTO MECHANIC (MECHANIC_ID, MECHANIC_LNAME, MECHANIC_FNAME, IS_AUTHORIZED) VALUES
(1, 'Taylor', 'James', TRUE),
(2, 'Anderson', 'Karen', TRUE),
(3, 'Thomas', 'Robert', FALSE),
(4, 'Jackson', 'Patricia', TRUE),
(5, 'White', 'Christopher', TRUE),
(6, 'Harris', 'Barbara', FALSE);

INSERT INTO MAINTENANCE_LOG (LOG_ID, VEHICLE_ID, DESCRIPTION, LOG_START_DATE, MAINTENANCE_COMPLETION_DATE, RELEASE_MECHANIC_ID) VALUES
(1, 4, 'Oil change', '2025-08-01', '2025-08-02', 1),
(2, 2, 'Brake replacement', '2025-08-03', '2025-08-05', 2),
(3, 1, 'Tire rotation', '2025-08-10', '2025-08-10', 4),
(4, 5, 'Hybrid system check', '2025-08-15', NULL, NULL),
(5, 6, 'Battery maintenance', '2025-08-20', '2025-08-21', 5),
(6, 3, 'Air filter replacement', '2025-08-25', '2025-08-26', 1);

INSERT INTO PART_TYPE (PART_ID, PART_NAME, QUANTITY_ON_HAND, MINIMUM_QUANTITY) VALUES
(1, 'Oil Filter', 50, 10),
(2, 'Brake Pads', 30, 5),
(3, 'Tire', 20, 4),
(4, 'Air Filter', 40, 8),
(5, 'Battery Pack', 5, 1),
(6, 'Spark Plug', 100, 20);

INSERT INTO MAINTENANCE_ITEM (LOG_ID, LINE_NUMBER, ITEM_DESCRIPTION, PART_ID, MECHANIC_ID) VALUES
(1, 1, 'Replace oil filter', 1, 1),
(2, 1, 'Install brake pads', 2, 2),
(3, 1, 'Rotate tires', 3, 4),
(4, 1, 'Inspect hybrid battery', 5, 5),
(5, 1, 'Replace battery pack', 5, 5),
(6, 1, 'Install new air filter', 4, 1);
